### ISSUE TITLE
getting Exception like System.ArgumentNullException: Value cannot be null.

### ISSUE THREAD

**Issue by Ajay12896** [rahulrathore44/Trx2Excel#1]
C:\Users\ajay.b\Downloads\Trx2Excel-master\Trx2Excel-master\Trx2Excel\bin\Debug> Trx2Excel.exe "C:\Users\ajay.b\Downloads\trx2html\sourceCode\sourceCode\TRX2HTML Solution-DEV10\trx2html\test\SampleTestResult.trx" "C:\Users\ajay.b\Downloads\abc.xlsx"

**I had used above text in Command line but it throws exception like : -**

Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at Trx2Excel.TrxReaderUtil.TrxReader.GetResult(XmlDocument doc, XmlNode node) in C:\Data\GitHub\Trx2Excel\Trx2Excel\TrxReaderUtil\TrxReader.cs:line 45
   at Trx2Excel.TrxReaderUtil.TrxReader.GetTestResults() in C:\Data\GitHub\Trx2Excel\Trx2Excel\TrxReaderUtil\TrxReader.cs:line 35
   at Trx2Excel.Program.Main(String[] args) in C:\Data\GitHub\Trx2Excel\Trx2Excel\Program.cs:line 21

plz help regarding to this issue.....

**Comment by scout208** [comment]
Can you try cloning the whole repo and building from scratch? I wonder if the build pushed to this repo is out of date.

**Comment by rahulrathore44** [comment]
@Ajay12896 Can you share the trx file? I have updated the excel package. Can you give it 1 more try?
@scout208  Thanks

**Comment by noamyogev84** [comment]
it happens when there's a result that is not in the Enum
for example "Not Executed"...
