### ISSUE TITLE
Unhandled Exception with long namespaces

### ISSUE THREAD

**Issue by svatal** [rahulrathore44/Trx2Excel#2]
If you are using long namespaces, you can run into folowing error:
```
Unhandled Exception: System.InvalidOperationException: A worksheet with this name already exists in the workbook : TestsCjm.Tests.HF_Upgrade.C1027
   at OfficeOpenXml.ExcelWorksheets.AddSheet(String Name, Boolean isChart, Nullable`1 chartType)
   at OfficeOpenXml.ExcelWorksheets.Add(String Name)
   at Trx2Excel.ExcelUtils.ExcelWriter.AddSheetToExcel(Dictionary`2 filteredData, ExcelPackage package, String nameSpace) in C:\Trx2Excel-master\Trx2Excel\ExcelUtils\ExcelWriter.cs:line 64
   at Trx2Excel.ExcelUtils.ExcelWriter.WriteToExcel(List`1 resultList) in C:\Trx2Excel-master\Trx2Excel\ExcelUtils\ExcelWriter.cs:line 56
   at Trx2Excel.Program.Main(String[] args) in C:\Trx2Excel-master\Trx2Excel\Program.cs:line 24
```
The program tries to create a new sheet for every namespace, but excel allows names with max length 31 characters and discards the rest. That can cause duplicit sheet names which results into beforementioned error.

**Workaround with limitation**
replace main content of `Trx2Excel.ExcelUtils.ExcelWriter.FilterTheDataWithNameSpace` with `return new Dictionary<string, List<UnitTestResult>> { { "Resuls", resultList } };` and recompile ...
which will display all results on single sheet

**Comment by rahulrathore44** [comment]
@svatal Thanks for pointing this issue. Do you mind sharing the pull request for this fix?

**Comment by svatal** [comment]
I do not consider my working around the issue as 'the fix'. I've just disabled a feature (splitting test into sheets by namespace - see the 'Workaround with limitation' paragraph in the report) that friend of mine didn't needed - that is not a material for a PR.
